---
title: "Processing RNAseq"
author: "Nicolas Veland"
format: html
editor: visual
---

# Processing RNAseq nfcore output file

Import and processing of nfcore output file into R for QC before DESEQ.

```{r}
#| echo: false

# Load libraries:
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggrepel)
library(data.table)
library(AnnotationDbi)
library(RColorBrewer)
library(viridis)
library(PCAtools)
library(patchwork)
library(ggpubr)
library(rstatix)


# Set working directory:
setwd("~/Documents/My_R")


# Create output_dir:
output_dir <- "/Users/velandn/Documents/My_R/Github_TEST/"
# output_dir <- "/Users/path/to/your/own/directory/of/analysis/output"

ifelse(!dir.exists(file.path(output_dir)),
       dir.create(file.path(output_dir)),
       "Directory Exists")

```

```{r}
######### I. Format rsem counts file for analysis.-----------------------------------

# 1. Read rsem counts data as dataframe:
Epidermis_Raw_Counts = read.delim(file= "~/Documents/My_R/Github_Cg1-KO/RNAseq/Epidermis_RNAseq/Epidermis_rsem.merged.gene_counts.tsv")
# read.delim is used for reading nfcore output rsem.merged.gene_counts.tsv files as dataframes
# REPLACE name of file according to tissue used (e.g. for EpiEpidermis use Epidermis_Raw_Counts)
# --> REPLACE "your/pathway/to/your/data/directory/that/contains/nfcore/output/rsem.merged.gene_counts.tsv 

# 2. Organize rsem counts dataframe:
row.names(Epidermis_Raw_Counts) = Epidermis_Raw_Counts[,1] 
# set rownames to be the first column from the counts data frame

Epidermis_Raw_Counts = as.matrix(Epidermis_Raw_Counts[,-1:-2]) 
# deselect the first two columns and convert to a matrix

Epidermis_Raw_Counts =  round(Epidermis_Raw_Counts) 
# round numerical values to integers


# 3. Create information table (colData file) as dataframe with correct row names:
Epidermis_colData = read.delim(file = "~/Documents/My_R/Github_Cg1-KO/RNAseq/Epidermis_RNAseq/Epidermis_colData.txt", row.names = 1)
# row.names = 1 --> sets rownames to be the first column from the colData frame
# Replace name of file according to tissue used (e.g. for EpiEpidermis use Epidermis_colData)
# --> REPLACE "your/pathway/to/your/data/directory/that/contains/colData.txt

# Check that rownames(Epi_colData) == colnames(Epi_Raw_Counts)
rownames(Epidermis_colData) == colnames(Epidermis_Raw_Counts)

# 4. Rename rownames of colData:
rownames(Epidermis_colData) = Epidermis_colData$Sample

# 5. Rename colnames of Raw_Counts:
colnames(Epidermis_Raw_Counts) = Epidermis_colData$Sample

# 6. Confirm that rownames(Epi_colData) == colnames(Epi_Raw_Counts)
rownames(Epidermis_colData) == colnames(Epidermis_Raw_Counts)



```

# Notes:

- Check both the Tissue_Raw_Counts and the TissueEpi_colData to verify format.

- If samples names look Ok, proceed to 02_normalization-QC.qmd script or to 04_DiffGeneExpression.qmd script.
