---
title: "Processing RNAseq"
author: "Nicolas Veland"
format: html
editor: visual
---

## Processing RNAseq nfcore output file

Processing of nfcore output file for QC before DESEQ.

```{r}
#| echo: false

# Load libraries:
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggrepel)
library(data.table)
library(AnnotationDbi)
library(RColorBrewer)
library(viridis)
library(PCAtools)
library(patchwork)
library(ggpubr)
library(rstatix)


# Set working directory:
setwd("~/Documents/My_R")


# Create output_dir:
output_dir <- "/Users/velandn/Documents/My_R/Github_TEST/"
# output_dir <- "/Users/path/to/your/own/directory/of/analysis/output"

ifelse(!dir.exists(file.path(output_dir)),
       dir.create(file.path(output_dir)),
       "Directory Exists")

```

```{r}
######### I. Format rsem counts file for analysis.-----------------------------------

# 1. Read rsem counts data as dataframe:
Tissue_Raw_Counts = read.delim(file = "/Users/velandn/Documents/My_R/DATA_BABS-DSL/RNAseq/Counts/Epidermis_2023.raw_counts.tsv") 
# read.delim is used for reading rsem.merged.gene_counts.tsv files as dataframes
# REPLACE name of file according to tissue used (e.g. for Epidermis use Epidermis_Raw_Counts)
# --> REPLACE "your/pathway/to/your/data/directory/that/contains/nfcore/output/rsem.merged.gene_counts.tsv 

# 2. Organize rsem counts dataframe:
row.names(Tissue_Raw_Counts) = Tissue_Raw_Counts[,1] 
# set rownames to be the first column from the counts data frame

Tissue_Raw_Counts = as.matrix(Tissue_Raw_Counts[,-1:-2]) 
# deselect the first two columns and convert to a matrix

Tissue_Raw_Counts =  round(Tissue_Raw_Counts) 
# round numerical values to integers

# 3. Remove specific samples/replicates from Counts dataframe: 
Tissue_Raw_Counts = Tissue_Raw_Counts[,-7] # Skin_Het_4 = column 7


# 4. Create information table (colData file) as dataframe with correct row names:
TissueEpi_colData = read.delim(file = "/Users/velandn/Documents/My_R/DATA_BABS-DSL/RNAseq/Counts/Epidermis_2023_colData.txt", row.names = 1) 
# row.names = 1 --> sets rownames to be the first column from the colData frame
# Replace name of file according to tissue used (e.g. for Epidermis use Epidermis_Raw_Counts)
# --> REPLACE "your/pathway/to/your/data/directory/that/contains/colData.txt

# 5. OPTIONAL: Remove specific samples/replicates from colData dataframe: 
TissueEpi_colData = TissueEpi_colData[-7,] # Skin_Het_4 = row 7

# 6. Rename colnames of Raw_Counts:
colnames(Tissue_Raw_Counts) = c("Skin_WT_1", "Skin_WT_2", "Skin_WT_4", "Skin_Het_1", "Skin_Het_2", "Skin_Het_3")

# 7. Rename rownames of colData:
rownames(TissueEpi_colData) = TissueEpi_colData$Sample

# 8. Confirm that rownames(Epi_colData) == colnames(Epi_Raw_Counts)
rownames(TissueEpi_colData) == colnames(Tissue_Raw_Counts)

# 9. Edit Epi_colData by adding Batch column:
TissueEpi_colData$Batch = c("1", "1", "2", "1", "1", "2")
```

Check both the Epi_Raw_Counts and the Epi_colData to verify format.

If samples names look Ok, proceed to QC script.
